name: 'Push Container Action'

description: 'Push built images to Docker Hub/OSG Harbor'

inputs:
  repo:
    description: 'Input string that gets passed along to the docker build args'
    required: true
  tag_list:
    description: 'List of tags that gets passed along to the docker build args'
    required: true
    default: '' # set to an empty string
  registry_url:
    description: 'Url of the registry action is loging in to'
    required: true
  username:
    description: 'Username of the registry obtained from secrets'
    required: true
  password:
    description: 'Password of the registry obtained from secrets'
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2

  - name: Generate tag list
    id: generate-tag-list
    env:
      REPO: ${{ inputs.repo }}
    run: |
      if [ -z "${{ inputs.tag_list }}" ]; then
        docker_repo=${GITHUB_REPOSITORY/opensciencegrid\/docker-/opensciencegrid/}
        tag_list=()
        for image_tag in "$REPO" "$REPO-$(date +%Y%m%d-%H%M)"; do
          tag_list+=("${{ inputs.resitry_url }}/$docker_repo":"$image_tag")
        done
        IFS=,
        echo "::set-output name=taglist::${tag_list[*]}"
      else
        tag_list=${{ inputs.tag_list }}
        echo "::set-output name=taglist::$tag_list"
      fi
    shell: bash

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Log in to ${{ inputs.registry_url }}
    uses: docker/login-action@v1
    with:
      registry: ${{ inputs.registry_url }}
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}

  - name: Build image
    uses: docker/build-push-action@v2.2.2
    with:
      push: true
      build-args: BASE_YUM_REPO=${{ inputs.repo }}
      tags: "${{ steps.generate-tag-list.outputs.taglist }}"
      cache-from: type=local,src=/tmp/.buildx-cache
  